### PR TITLE
Bump eslint version

### LINKED ISSUE #168: Bump eslint version
Bumped versions from:

- @typescript-eslint/eslint-plugin
- @typescript-eslint/parser
- eslint
- eslint-plugin-import

### PR DESCRIPTION
**Pull request by jorgebodega**
Resolves #168

### CODE REVIEW

**Review by RaphaelWoude — APPROVED** [review]
Looks good to me!
Do note that v8 of eslint does not support Node.js version 10. 
https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0

**Comment by jorgebodega** [comment]
> LGTM! Do note that v8 of eslint does not support Node.js version 10. [eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0)

I know it. That is another check to do. Even node is not supporting 10.x, and semantic release needs 14.x.

The ideal? Drop support to everything that is less than 14, because is the current LTS until 16. Then, support both

**Comment by RaphaelWoude** [comment]
Dropping support up until 14 is probably the best for the next version.

**Comment by jorgebodega** [comment]
https://github.com/w3tecch/typeorm-seeding/issues/161#issuecomment-941638754

I think this will be the proper way

**Pull request merged**
